name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
  
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack nuget Package
        run: dotnet pack Clubhouse.io.net/Clubhouse.io.net.csproj --configuration Release --include-source --include-symbols
      - name: Push package to nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json   
